version: 2
jobs:
  test_regression_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r model_package/requirements.txt
            chmod +x ./scripts/fetch_kaggle_dataset.sh
            ./scripts/fetch_kaggle_dataset.sh
            py.test -vv model_package/tests
  test_ml_api:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r model_api/requirements.txt
            py.test -vv model_api/tests
  train_and_upload_regression_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Setup env
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -r model_package/requirements.txt
      - run:
          name: Publish model
          command: |
            . venv/bin/activate
            chmod +x ./scripts/fetch_kaggle_dataset.sh ./scripts/publish_model.sh
            ./scripts/fetch_kaggle_dataset.sh
            PYTHONPATH=./model_package python3 model_package/modeling_pipeline/train_pipeline.py
            ./scripts/publish_model.sh ./model_package/
workflows:
  version: 2
  test-all:
    jobs:
      - test_regression_model
      - test_ml_api
      - train_and_upload_regression_model
      - test_ml_api:
          requires:
            - train_and_upload_regression_model